### ISSUE TITLE
There seems to be a duplicity with eigen code

### ISSUE THREAD

**Issue by mirek-fidler** [anboto/Anboto#1]
https://github.com/anboto/Anboto/tree/master/plugin/eigen

There is a subfolder src, then subfolder Eigen with another src again and seemingly same files. Maybe some of them needs to be deleted?

**Comment by izabala123** [comment]
Thank you Mirek, you are right. Hopefully removed.

**Comment by izabala123** [comment]
As it has been a long time since this problem has been solved and there are no further comments, this issue will be closed.
