### ISSUE TITLE
Compiling   "ScatterCtrl_demo" in linux fails.

### ISSUE THREAD

**Issue by andrew313** [anboto/Anboto#10]
In the compilation routine "ScatterCtrl_demo" could not pass.

os:

Linux archlinux64 5.17.5-arch1-1 #1 SMP PREEMPT Wed, 27 Apr 2022 20:56:11 +0000 x86_64 GNU/Linux

Error message:
``
/home/andrew/opt/upp/.cache/upp.out/MyApps_MyApps/ScatterCtrl/CLANG.Debug.Debug_Full.Gui.Shared/ScatterCtrl$blitz.cpp (3): In file included from /home/andrew/opt/upp/.cache/upp.out/MyApps_MyApps/ScatterCtrl/CLANG.Debug.Debug_Full.Gui.Shared/ScatterCtrl$blitz.cpp:3:
/home/andrew/opt/Anboto/ScatterCtrl/Processing.cpp (3): In file included from /home/andrew/opt/Anboto/ScatterCtrl/Processing.cpp:3:
/home/andrew/opt/Anboto/ScatterCtrl/ScatterCtrl.h (6): In file included from /home/andrew/opt/Anboto/ScatterCtrl/ScatterCtrl.h:6:
/home/andrew/opt/Anboto/ScatterDraw/ScatterDraw.h (13): In file included from /home/andrew/opt/Anboto/ScatterDraw/ScatterDraw.h:13:
/home/andrew/opt/Anboto/Functions4U/Functions4U.h (1361): error: class member cannot be redeclared
/home/andrew/opt/Anboto/Functions4U/Functions4U.h (1328): error: use of undeclared identifier 'SetConsoleOutputCP'
/home/andrew/opt/Anboto/Functions4U/Functions4U.h (1330): error: unknown type name 'HANDLE'
/home/andrew/opt/Anboto/Functions4U/Functions4U.h (1330): error: use of undeclared identifier 'STD_OUTPUT_HANDLE'
/home/andrew/opt/Anboto/Functions4U/Functions4U.h (1361): error: class member cannot be redeclared
/home/andrew/opt/Anboto/Functions4U/Functions4U.h (1328): error: use of undeclared identifier 'SetConsoleOutputCP'
/home/andrew/opt/Anboto/Functions4U/Functions4U.h (1330): error: unknown type name 'HANDLE'
/home/andrew/opt/Anboto/Functions4U/Functions4U.h (1330): error: use of undeclared identifier 'STD_OUTPUT_HANDLE'

``
I'm trying to use trend curves in an application, without much source code modification capability, I've tried to add, #define PLATFORM_POSIX in main.cpp, but it doesn't work.
You can see if I am using it incorrectly, or if there is another problem.
In addition, the same DEMO program compiles in WINDOWS without any problem.

**Comment by andrew313** [comment]
----- CtrlLib ( GUI CLANG DEBUG SHARED DEBUG_FULL BLITZ POSIX LINUX ) (1 / 22)
BLITZ: LabelBase.cpp DisplayPopup.cpp Button.cpp Switch.cpp EditField.cpp Text.cpp LineEdit.cpp DocEdit.cpp ScrollBar.cpp HeaderCtrl.cpp ArrayCtrl.cpp MultiButton.cpp PopupTable.cpp DropL
    ist.cpp DropChoice.cpp Static.cpp Splitter.cpp FrameSplitter.cpp SliderCtrl.cpp ColumnList.cpp Progress.cpp AKeys.cpp RichTextView.cpp Prompt.cpp Help.cpp DateTimeCtrl.cpp SuggestCtrl
    .cpp Bar.cpp MenuItem.cpp MenuBar.cpp ToolButton.cpp ToolBar.cpp ToolTip.cpp StatusBar.cpp TabCtrl.cpp TreeCtrl.cpp DropTree.cpp DlgColor.cpp ColorPopup.cpp ColorPusher.cpp FileList.c
    pp FileSel.cpp FileSelUtil.cpp PrinterJob.cpp Windows.cpp Win32.cpp Gtk.cpp TrayIconWin32.cpp TrayIconX11.cpp TrayIconGtk.cpp Update.cpp CtrlUtil.cpp LNGCtrl.cpp Ch.cpp ChGtk3.cpp ChC
    oco.cpp
CtrlLibInit.cpp
ChWin32.cpp
----- Report ( GUI CLANG DEBUG SHARED DEBUG_FULL BLITZ POSIX LINUX ) (2 / 22)
Report.cpp
ReportDlg.cpp
----- PdfDraw ( GUI CLANG DEBUG SHARED DEBUG_FULL BLITZ POSIX LINUX ) (3 / 22)
BLITZ: TTFStream.cpp TTFStruct.cpp TTFSubset.cpp TTFReader.cpp PdfReport.cpp PdfInit.icpp
PdfDraw.cpp
----- ScatterCtrl ( GUI CLANG DEBUG SHARED DEBUG_FULL BLITZ POSIX LINUX ) (4 / 22)
BLITZ: Processing.cpp Properties.cpp Data.cpp PopUpText.cpp PieCtrl.cpp
ScatterCtrl.cpp
PdfDraw: 7 file(s) built in (0:03.17), 453 msecs / file
----- CtrlCore ( GUI CLANG DEBUG SHARED DEBUG_FULL BLITZ POSIX LINUX ) (5 / 22)
BLITZ: SystemDraw.cpp Frame.cpp CtrlMt.cpp Ctrl.cpp CtrlChild.cpp CtrlPos.cpp CtrlDraw.cpp CtrlMouse.cpp CtrlKbd.cpp CtrlTimer.cpp CtrlClip.cpp LocalLoop.cpp Preedit.cpp TopWindow.cpp DrawWin3
    2.cpp DrawOpWin32.cpp DrawTextWin32.cpp ImageWin32.cpp MetaFile.cpp UtilWin32.cpp Win32Ctrl.cpp Win32Wnd.cpp Win32Clip.cpp Win32DnD.cpp Win32Proc.cpp TopWin32.cpp DHCtrl.cpp DrawX11.cpp Dr
    awOpX11.cpp DrawTextX11.cpp ImageX11.cpp UtilX11.cpp X11Ctrl.cpp X11Wnd.cpp X11Proc.cpp X11Clip.cpp X11DnD.cpp X11Top.cpp X11ImgClip.cpp X11App.cpp X11DHCtrl.cpp GtkDrawOp.cpp GtkDrawText.
    cpp GtkDrawImage.cpp GdkImage.cpp GtkUtil.cpp GtkX11Util.cpp GtkCtrl.cpp GtkCapture.cpp GtkWnd.cpp GtkCreate.cpp GtkEvent.cpp GtkTop.cpp GtkClip.cpp GtkDnD.cpp GtkApp.cpp CocoCtrl.cpp Coco
    Wnd.cpp CocoTop.cpp CocoChSysInit.cpp ParseRTF.cpp EncodeRTF.cpp
Report: 2 file(s) built in (0:06.52), 3264 msecs / file
CtrlCoreInit.cpp
In file included from /home/andrew/opt/upp/.cache/upp.out/MyApps_MyApps/ScatterCtrl/CLANG.Debug.Debug_Full.Gui.Shared/ScatterCtrl$blitz.cpp:3:
In file included from /home/andrew/opt/Anboto/ScatterCtrl/Processing.cpp:3:
In file included from /home/andrew/opt/Anboto/ScatterCtrl/ScatterCtrl.h:6:
In file included from /home/andrew/opt/Anboto/ScatterDraw/ScatterDraw.h:13:
/home/andrew/opt/Anboto/Functions4U/Functions4U.h:1361:19: error: class member cannot be redeclared
        virtual   void   Flush()       { fflush(stdout); }
                         ^
/home/andrew/opt/Anboto/Functions4U/Functions4U.h:1326:7: note: previous definition is here
        void Flush() {
             ^
/home/andrew/opt/Anboto/Functions4U/Functions4U.h:1328:4: error: use of undeclared identifier 'SetConsoleOutputCP'
                        SetConsoleOutputCP(65001); // set console to UTF8 mode
                        ^
/home/andrew/opt/Anboto/Functions4U/Functions4U.h:1330:10: error: unknown type name 'HANDLE'
                static HANDLE h = GetStdHandle(STD_OUTPUT_HANDLE);
                       ^
/home/andrew/opt/Anboto/Functions4U/Functions4U.h:1330:34: error: use of undeclared identifier 'STD_OUTPUT_HANDLE'
                static HANDLE h = GetStdHandle(STD_OUTPUT_HANDLE);
                                               ^
4 errors generated.
CtrlLib: 58 file(s) built in (0:11.37), 196 msecs / file
4 errors generated.
In file included from /home/andrew/opt/Anboto/ScatterCtrl/ScatterCtrl.cpp:3:
In file included from /home/andrew/opt/Anboto/ScatterCtrl/ScatterCtrl.h:6:
In file included from /home/andrew/opt/Anboto/ScatterDraw/ScatterDraw.h:13:
/home/andrew/opt/Anboto/Functions4U/Functions4U.h:1361:19: error: class member cannot be redeclared
        virtual   void   Flush()       { fflush(stdout); }
                         ^
/home/andrew/opt/Anboto/Functions4U/Functions4U.h:1326:7: note: previous definition is here
        void Flush() {
             ^
/home/andrew/opt/Anboto/Functions4U/Functions4U.h:1328:4: error: use of undeclared identifier 'SetConsoleOutputCP'
                        SetConsoleOutputCP(65001); // set console to UTF8 mode
                        ^
/home/andrew/opt/Anboto/Functions4U/Functions4U.h:1330:10: error: unknown type name 'HANDLE'
                static HANDLE h = GetStdHandle(STD_OUTPUT_HANDLE);
                       ^
/home/andrew/opt/Anboto/Functions4U/Functions4U.h:1330:34: error: use of undeclared identifier 'STD_OUTPUT_HANDLE'
                static HANDLE h = GetStdHandle(STD_OUTPUT_HANDLE);
                                               ^
ScatterCtrl: 6 file(s) built in (0:07.86), 1311 msecs / file
CtrlCore: 63 file(s) built in (0:07.05), 111 msecs / file

There were errors. (0:13.78)

**Comment by izabala123** [comment]
Hello Andrew313

I think this problem is solved. Please confirm. Thank you.

Best regards
Iñaki
