### ISSUE TITLE
Non-linked ZoomToFit

### ISSUE THREAD

**Issue by Maginor** [anboto/Anboto#4]
Hi,
Is it possible to have a Non-linked version of ZoomToFit, or alternatively let non-linked be the default behaviour and have a separate ZoomToFitLinked like you have for SetRangeLinked etc.
I could make a pull request myself, but I don't know which option you would prefer.

**Comment by izabala123** [comment]
As I understand you, you have a set of ScatterDraw/ScatterCtrl linked, but for a specific issue, you want to zoom in on one of them without affecting the rest. Is this the case?

**Comment by Maginor** [comment]
Yes. I have a set of linked ScatterCtrls, and I specifically want to call the ZoomToFit function of one of them without affecting the others.

**Comment by izabala123** [comment]
Perfect. New ZoomToFitNonLinked, ZoomNonLinked and ScrollNonLinked functions are added.
Sorry for the delay, I have a problem with Github notifications.

**Comment by Maginor** [comment]
Great, thanks!
