### ISSUE TITLE
DrawCircle redefines CtrlLib .usc

### ISSUE THREAD

**Issue by mirek-fidler** [anboto/Anboto#6]
https://github.com/anboto/Anboto/blob/131d7879a43b82759ac0f53d3234496039d3aa1e/ScatterCtrl/ScatterCtrl.usc#L202

DrawCircle is already defined in CtrlLib. This definition kills Switch rendering in layout designer. I recommend to rename to DrawCircle2.

**Comment by izabala123** [comment]
Fixed. Thank you.
