### ISSUE TITLE
OfficeAutomation MatrixSet is incorrect

### ISSUE THREAD

**Issue by Maginor** [anboto/Anboto#9]
Hi,

The current implementation of MatrixGet just returns a matrix filled with empty values. I don't know if this was tested and worked correctly on some platforms, but it doesn't work for me (Windows10).

This is probably because the matrix is not filled with the values in the selected range. 

To get it to work correctly you have to do something like the following (it should be cleaned up more with error checks...)
I have not tested the suggested fix in upp in particular, but I got something similar to work by implementing it from the ground up.

```
if (!Select(fromX, fromY, toX, toY)) return false;
VariantOle Matrix = Ole::GetVariant(Range, "Value");    //Need to make a version of GetValue (called GetVariant) that does not convert the VARIANT to an upp Value but to a VariantOle instead..
for (int row = 0; row < height; ++row)
	for (int col = 0; col < width; ++col)
		if (!Matrix.ArrayGetValue(col + 1, row + 1, data[row][col]))  throw;
Matrix.ArrayDestroy();
// Don't call MatrixSetSelection since that overwrites the selection in the loaded sheet with the given matrix. Not technically a problem if the matrix loaded correctly from that range in the first place, but it is unnecessary work.
```

**Comment by izabala123** [comment]
Hi Maginor

Thank you for your report. Please review if it works now.

Iñaki

**Comment by Maginor** [comment]
Hi, I can't see that any changes have been made to the MatrixGet function, and it still doesn't work.
(note that I incorrectly report MatrixSet in the title of the issue. It is MatrixGet that doesn't seem to work).

**Comment by izabala123** [comment]
Hi Maginor

Thank you, your proposal is right. I have implemented it and works properly. 
Sorry for the previous misunderstanding. Initially I thought the problem came from other fix.

Iñaki
